### ISSUE TITLE
Are you banned?

### ISSUE THREAD

**Issue by BorkBorkGoesTheCode** [DangerNoodle/Cataclysm-DDA#3]
Are you banned? Sorry for using the issue system to ask, @DangerNoodle .

**Comment by DangerNoodle** [comment]
Blocked from repository following closure of https://github.com/CleverRaven/Cataclysm-DDA/pull/21503

Will no longer be available to maintain Extended Realistic Weapons.

My apologies.

**Comment by BorkBorkGoesTheCode** [comment]
Would you like me to host a copy of Extended Realistic Guns in my own repo?

**Comment by DangerNoodle** [comment]
I do not know at present what would be best.

**Comment by BorkBorkGoesTheCode** [comment]
I'm going to start uploading a version of Experimental Realistic Guns to my repo.
